### ISSUE TITLE
web support

### ISSUE THREAD

**Issue by vghfr** [CookeyLang/CookeyLang#13]
it would be cool to be able to set up HTTP servers and have HTML support, like js or c#

**Comment by cursorweb** [comment]
Indeed it is! What do you recommend our code design look like?

**Comment by vghfr** [comment]
```
var web = new cookeyWeb();
% idk if this is correct syntax lol %
web.get(directory)
respose.write("Hello!")
response.use(./index.html)
```
could use some work though
kinda like an express type thing

**Comment by cursorweb** [comment]
sure! I'll implement that
