### ISSUE TITLE
Join

### ISSUE THREAD

**Issue by whippingdot** [CookeyLang/CookeyLang#15]
Hey, two questions
1. R u still working on this or is it finished and not going to be worked on
2. Can I join the org. i wanna help mainly with the CSS of ur website as a few colors are not noice

EDIT:
Oh and 3. Is it called quicken or is it called cookeylang now...

**Comment by cursorweb** [comment]
1. Development is mostly moved to cookeylang-ts
2. Yeah sure
3. Quiken or CookeyLang? Idk its very hard to change the name

**Comment by whippingdot** [comment]
thanks for replying almost 4 months later!

lul but thanks for replying really

**Comment by RaidTheWeb** [comment]
close for inactivity :)

**Comment by whippingdot** [comment]
Am I in the org or not
